# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build-java8:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo/java8

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn package

      - persist_to_workspace:
          root: ~/repo
          paths:
            - java8/target/java8-dev.jar
            - java8/serverless.yml

  build-java11:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo/java11

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn package

      - persist_to_workspace:
          root: ~/repo
          paths:
            - java11/target/java11-dev.jar
            - java11/serverless.yml


  deploy-java11:
    docker:
    - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ~/repo

      - restore_cache:
          keys:
            - v1-dependencies-node-serverless-1-61-2-serverless-domain-manager-3-3-1

      - run: npm install serverless@1.61.2 serverless-domain-manager@3.3.1

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-node-serverless-1-61-2-serverless-domain-manager-3-3-1

      - run:
          name: Deploy to AWS
          command: |
            cd java11
            ../node_modules/serverless/bin/serverless deploy


  deploy-java8:
    docker:
    - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ~/repo

      - restore_cache:
          keys:
            - v1-dependencies-node-serverless-1-61-2-serverless-domain-manager-3-3-1

      - run: npm install serverless@1.61.2 serverless-domain-manager@3.3.1

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-node-serverless-1-61-2-serverless-domain-manager-3-3-1

      - run:
          name: Deploy to AWS
          command: |
            cd java8
            ../node_modules/serverless/bin/serverless deploy

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-java8
      - build-java11
      - deploy-java8:
          requires:
            - build-java8
      - deploy-java11:
          requires:
            - build-java11