# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build-java8:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo/java8

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn package

      - persist_to_workspace:
          root: ~/repo
          paths:
            - java8/target/java8-dev.jar
            - java8/serverless.yml


  serverless-deploy:
    docker:
    - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ~/repo

      - restore_cache:
          keys:
            - v1-dependencies-node-serverless

      - run: npm install serverless

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-node-serverless

      - run:
          name: Deploy to AWS
          command: ./node_modules/serverless/bin/serverless deploy

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-java8
      - serverless-deploy:
          requires:
            - build-java8